### ISSUE TITLE
Rclone formula

### ISSUE THREAD

**Issue by dnicolson** [gromgit/homebrew-fuse#9]
FUSE support was [removed](https://github.com/Homebrew/homebrew-core/commit/d2881ce74eb0293594f4c60650bc04a33c97390f#diff-089c237d356eb3a5a1cd9ead5822599d7d4352e23733fa5e3091e25ba3d297f6) from Rclone in Homebrew core in late 2020. Should this formula be part of this tap?

**Comment by gromgit** [comment]
Added `rclone-mac` without bottles for now - the binary is somehow getting corrupted when bottled. Let me know if it works for you.

**Comment by dnicolson** [comment]
Thanks for the quick addition! The binary is named `rclone-mac` instead of `rclone` though.

**Comment by gromgit** [comment]
Yes. This is to avoid a situation where a user installs a formula that depends on the core `rclone` formula, which would cause a confusing link failure. Declaring a `conflicts_with` on `rclone` causes the opposite problem, where users can't install `rclone-mac` because they've already installed `rclone` either directly or indirectly.

**Comment by dnicolson** [comment]
I'm not sure if I fully understand, how come the `SshfsMac` formula produces the binary `sshfs` and not `sshfs-mac`?

**Comment by gromgit** [comment]
All the other formulae can be installed safely, because their corresponding core tap formulae can't be installed on macOS anyway.

Core `rclone` still exists, and is a dependent of several other formulae, so leaving `rclone-mac`'s binary name as `rclone` pretty much guarantees conflicts and issues posted against _Homebrew core_, which I'd very much want to avoid.

**Comment by gromgit** [comment]
That said, I've just pushed an update that takes a cue from the `coreutils` formula, and aliases `rclone-mac` to `rclone` in a separate directory.
